### ISSUE TITLE
Broken default pm settings

### ISSUE THREAD

**Issue by dincho** [NBZ4live/ansible-php-fpm#15]
This role cannot be installed with default settings on servers with 1 virtual CPU.
regression in https://github.com/wiredcraft-ops/ansible-php-fpm/commit/617b52bd8f32d507262db7281d63f2abe17317e3 where

* pm.max_children is set based on server vcpus
* pm.max_spare_servers is kept 3

thus when vcpu = 1, max_children is 2, but max_spare is 3
logically PHP FPM does not allow setting max_spare > max_children

either https://github.com/wiredcraft-ops/ansible-php-fpm/commit/617b52bd8f32d507262db7281d63f2abe17317e3 should be reverted or default max_spare should be set to 2

@NBZ4live what do you prefer?

**Comment by NBZ4live** [comment]
This is already done in PR https://github.com/NBZ4live/ansible-php-fpm/pull/12/files

**Comment by dincho** [comment]
@NBZ4live I think you misunderstood this. #12 broke it! Please re-read the issue.
