### ISSUE TITLE
Role doesn't work out-of-the-box on Ubuntu 16.04 (php7)

### ISSUE THREAD

**Issue by j4m3s** [NBZ4live/ansible-php-fpm#19]
This is due to the default `php_fpm_apt_packages` specifying php5-fpm, which is not available on the later versions of Ubuntu.  The packages are now available as php-fpm, which then includes php7 dependencies.  The same (the 5 is dropped) applies to other packages such as php-cli.

There are a variety of changes required to accommodate php7 - several paths have changed too.  It may make sense to add a var to specify whether v5 or v7 should be installed.

**Comment by NBZ4live** [comment]
A new version can be found in the "feature/ppa" branch (version 2.0.0-beta1).
It installs PHP from Ondrej's PPA repository and works on all Ubuntu versions from 12.04
