### ISSUE TITLE
debian apt_repository not using the right repo ?

### ISSUE THREAD

**Issue by Notmarrco** [NBZ4live/ansible-php-fpm#25]
Hello,

I had an error while executing the install task for debian jessie.

It works when I use 
```
- name: Add DEB repository (Debian)
  apt_repository: repo='deb https://packages.sury.org/php/ jessie main' state=present filename='ondrej'
```
 instead of ```stable main``` .

We also have to get the repo key, as mentioned in the README file : https://packages.sury.org/php/README.txt 

is it an issue or do I miss something ?

thanks

**Comment by NBZ4live** [comment]
Fixed in 2.0.1
