### ISSUE TITLE
Error installing php packages

### ISSUE THREAD

**Issue by salemgolemugoo** [NBZ4live/ansible-php-fpm#26]
I have an error: failed: [findyourdressnew] (item=[u'php_fpm_apt_packages']) => {"failed": true, "item": ["php_fpm_apt_packages"], "msg": "No package matching 'php_fpm_apt_packages' is available"}

My playbook for this role:
```
    - role: nbz4live.php-fpm
      php_fpm_apt_packages:
        - php5-fpm
        - php5-cli
        - php5-imagick
        - php5-memcached
        - php5-gd
        - php5-intl
        - php5-mysql
        - php5-curl
        - php-apc
        - php5-dev
        - php-pear
```

**Comment by NBZ4live** [comment]
The role was stitched to use ondrej PPA.
The package name must be php5.6-fpm, etc.
