### ISSUE TITLE
Bug with Python 3

### ISSUE THREAD

**Issue by d9pouces** [NBZ4live/ansible-php-fpm#29]
In file templates/pool.conf.j2, 
the line `{% for directive, value in ((php_fpm_pool_defaults|default(dict())).items() + item.items()) if directive != "name" %}` is invalid: dict().items() is not a list anymore, it's an iterator.

Maybe you should replace it by something like `{% for directive, value in ((php_fpm_pool_defaults|default(dict()).items()|list) + (item.items()|list)) if directive != "name" %}
`

**Comment by NBZ4live** [comment]
Should be solved with #37
