### ISSUE TITLE
listen.owner, listen.user, listen.mode are not configurable and causes error for socket

### ISSUE THREAD

**Issue by o10g** [NBZ4live/ansible-php-fpm#33]
Should be able to configure these three directives:

```
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
```

Without them socket is created from root which causes the error:

`*12 connect() to unix:/var/run/php5-fpm.sock failed (13: Permission denied) while connecting to upstream`

**Comment by NBZ4live** [comment]
Hi,

it is possible in the php_fpm_pool_defaults and php_fpm_config variables.
At least in the newer versions.

Just use like:
```
php_fpm_pools:
 - name: foo
   user: www-data
   group: www-data
   listen: /my/socket/path
   listen. owner: www-data
   listen.group = www-data
   listen.mode = 0660
   chdir: /
```
PS: PHP 5 is not supported for long time already.
