### ISSUE TITLE
ansible galaxy installs 0.2.6 version.

### ISSUE THREAD

**Issue by klemenkobetic** [NBZ4live/ansible-php-fpm#9]
ansible galaxy installs 0.2.6 version. please update

sudo ansible-galaxy install nbz4live.php-fpm
- downloading role 'php-fpm', owned by nbz4live
- downloading role from https://github.com/NBZ4live/ansible-php-fpm/archive/0.2.6.tar.gz
- extracting nbz4live.php-fpm to /etc/ansible/roles/nbz4live.php-fpm
- nbz4live.php-fpm was installed successfully

**Comment by NBZ4live** [comment]
Thank you. Done
